songifi/gg_server

gasless-gossip/.gitignore
gasless-gossip/src/config/exceptions/config.exceptions.ts
gasless-gossip/src/main.ts
gasless-gossip/src/utils/global-exception-filter.ts

This pull request enhances the NestJS application by introducing a centralized error handling system designed to improve reliability and maintainability. The key changes include:
- **Global Exception Filter**: Added a `GlobalExceptionFilter` to catch all unhandled exceptions across the application, ensuring consistent error responses and mapping exceptions to appropriate HTTP status codes while logging errors with relevant details.
- **Custom Exception Classes**: Introduced specific custom exceptions such as `ValidationException`, `NotFoundException`, and `AuthenticationException` to manage distinct error scenarios with tailored HTTP status codes and messages.
- **Logging Integration**: Integrated the global filter with the `LoggingService` to log errors, capturing stack traces for …

Implement Centralized Error Handling with Custom Exceptions and Global Filters

---

gasless-gossip/nest-cli.json
gasless-gossip/package-lock.json
gasless-gossip/package.json
gasless-gossip/src/auth/auth.controller.ts
gasless-gossip/src/main.ts

This PR adds a comprehensive API documentation using Swagger/OpenAPI

feat: add Swagger integration for API documentation

---

gasless-gossip/src/modules/user/dto/create-user.dto.ts
gasless-gossip/src/modules/user/dto/update-user.dto.ts
gasless-gossip/src/modules/user/dto/user-profile.dto.ts
gasless-gossip/src/modules/user/dto/user-response.dto.ts
gasless-gossip/src/modules/user/enums/user-role.enum.ts
gasless-gossip/src/modules/user/enums/user-status.enum.ts
gasless-gossip/src/modules/user/interfaces/user.interface.ts
gasless-gossip/src/modules/user/schemas/user.schema.ts

UserResource/DTO Models

---

gasless-gossip/src/messaging/dto/create-attachment.dto.ts
gasless-gossip/src/messaging/dto/create-message.dto.ts
gasless-gossip/src/messaging/dto/create-token-transfer.dto.ts
gasless-gossip/src/messaging/dto/message-response.dto.ts
gasless-gossip/src/messaging/dto/update-message-status.dto.ts
gasless-gossip/src/messaging/enums/message-status.enum.ts
gasless-gossip/src/messaging/enums/message-type.enum.ts
gasless-gossip/src/messaging/interfaces/attachment.interface.ts
gasless-gossip/src/messaging/interfaces/message-receipt.interface.ts
gasless-gossip/src/messaging/interfaces/message.interface.ts
gasless-gossip/src/messaging/interfaces/reaction.interface.ts
gasless-gossip/src/messaging/interfaces/token-transfer.interface.ts
gasless-gossip/src/messaging/schemas/message.schema.ts

feat: Message Resource Definition

---

gasless-gossip/src/user/tests/user.controller.spec.ts
gasless-gossip/src/user/tests/user.e2e-spec.ts
gasless-gossip/src/user/tests/user.service.spec.ts
gasless-gossip/src/user/user.controller.ts
gasless-gossip/src/user/user.module.ts
gasless-gossip/src/user/user.service.ts

worked on the user service and controller implementation

---

gasless-gossip/package-lock.json
gasless-gossip/package.json
gasless-gossip/src/app.module.ts
gasless-gossip/src/messaging/interfaces/authenticated-request.interface.ts
gasless-gossip/src/messaging/message.controller.ts
gasless-gossip/src/messaging/message.module.ts
gasless-gossip/src/messaging/messageRepository/message.Respository.ts
gasless-gossip/src/messaging/messgaeRespositoryUnitTest/messsage-Respository-unit-test.ts
gasless-gossip/src/messaging/providers/message.Service.ts
gasless-gossip/src/messaging/schemas/message.schema.ts

Message Entity and Repository Implementation

Message entity repository

---

gasless-gossip/src/app.module.ts
gasless-gossip/src/conversation/conversation.controller.ts
gasless-gossip/src/conversation/conversation.module.ts
gasless-gossip/src/conversation/dtos/conversation-response.dto.ts
gasless-gossip/src/conversation/dtos/creategroup-conversation.dto.ts
gasless-gossip/src/conversation/dtos/direct-conversation.dto.ts
gasless-gossip/src/conversation/dtos/updategroup-conversation.ts
gasless-gossip/src/conversation/dtos/validation.dto.ts
gasless-gossip/src/conversation/enums/conversation.enum.ts
gasless-gossip/src/conversation/interfaces/conversation.interface.ts
gasless-gossip/src/conversation/providers/conversation.service.ts
gasless-gossip/src/conversation/schema/conversation.schema.ts

the conversation resource model, including properties, relationships, and DTOs for both direct and group conversations has been successfully created.

conversation resource created

---

gasless-gossip/package-lock.json
gasless-gossip/package.json
gasless-gossip/src/app.module.ts
gasless-gossip/src/authentication/authentication.module.ts
gasless-gossip/src/authentication/decorator/current-user.decorator.ts
gasless-gossip/src/authentication/decorator/roles.decorator.ts
gasless-gossip/src/authentication/guards/jwt.guard.ts
gasless-gossip/src/authentication/guards/roles.guard.ts
gasless-gossip/src/authentication/middleware/authentication.middleware.ts
gasless-gossip/src/authentication/strategies/jwt.strategy.ts
gasless-gossip/src/common/enums/roles.enums.ts
gasless-gossip/src/messaging/dto/create-attachment.dto.ts
gasless-gossip/src/messaging/dto/create-message.dto.ts
gasless-gossip/src/messaging/dto/create-token-transfer.dto.ts
gasless-gossip/src/messaging/dto/message-response.dto.ts
gasless-gossip/src/messaging/dto/update-message-status.dto.ts
gasless-gossip/src/messaging/schemas/message.schema.ts
gasless-gossip/src/modules/user/schemas/user.schema.ts
gasless-gossip/test/guards/jwt-auth.guard.spec.ts
gasless-gossip/test/guards/roles.guard.spec.ts
gasless-gossip/tsconfig.json

pulling updated code from main branch

---

gasless-gossip/src/user-search/dto/search-user.dto.ts
gasless-gossip/src/user-search/dto/user-search-response.dto.ts
gasless-gossip/src/user-search/tests/user-search.controller.spec.ts
gasless-gossip/src/user-search/tests/user-search.e2e-spec.ts
gasless-gossip/src/user-search/tests/user-search.service.spec.ts
gasless-gossip/src/user-search/user-search.controller.ts
gasless-gossip/src/user-search/user-search.module.ts
gasless-gossip/src/user-search/user-search.service.ts

feat: User Search Service resource including controllers and dto

---

gasless-gossip/src/modules/user/leaderboard/dto/user-stats-response.dto.ts
gasless-gossip/src/modules/user/leaderboard/enums/leaderboard-category.enum.ts
gasless-gossip/src/modules/user/leaderboard/enums/time-period.enum.ts
gasless-gossip/src/modules/user/leaderboard/interfaces/leaderboard-response.dto.ts
gasless-gossip/src/modules/user/leaderboard/interfaces/transaction-stats.interface.ts
gasless-gossip/src/modules/user/leaderboard/leaderboard.controller.ts
gasless-gossip/src/modules/user/leaderboard/leaderboard.module.ts
gasless-gossip/src/modules/user/leaderboard/leaderboard.service.ts
gasless-gossip/src/modules/user/leaderboard/schemas/daily-stats.schema.ts
gasless-gossip/src/modules/user/leaderboard/schemas/leaderboard-cache.schema.ts
gasless-gossip/src/modules/user/leaderboard/schemas/transaction-stats.schema.ts
gasless-gossip/src/modules/user/leaderboard/tests/leaderboard.service.spec.ts

created token transation leaderboard

---

gasless-gossip/src/achievements/achievements.controller.ts
gasless-gossip/src/achievements/achievements.module.ts
gasless-gossip/src/achievements/achievements.service.ts
gasless-gossip/src/achievements/dto/achievement-response.dto.ts
gasless-gossip/src/achievements/dto/create-achievement.dto.ts
gasless-gossip/src/achievements/dto/create-badge.dto.ts
gasless-gossip/src/achievements/dto/update-progress.dto.ts
gasless-gossip/src/achievements/dto/user-achievement-response.dto.ts
gasless-gossip/src/achievements/enums/achievement-category.enum.ts
gasless-gossip/src/achievements/enums/achievement-rarity.enum.ts
gasless-gossip/src/achievements/enums/achievement-type.enum.ts
gasless-gossip/src/achievements/interfaces/achievement.interface.ts
gasless-gossip/src/achievements/interfaces/badge.interface.ts
gasless-gossip/src/achievements/interfaces/user-achievement.interface.ts
gasless-gossip/src/achievements/listeners/achievement.listener.ts
gasless-gossip/src/achievements/schemas/achievement.schema.ts
gasless-gossip/src/achievements/schemas/badge.schema.ts
gasless-gossip/src/achievements/schemas/user-achievement.schema.ts
gasless-gossip/src/achievements/tests/achievements.service.spec.ts

achievement-and-badge-system

---

gasless-gossip/src/reputation/dto/reputation-history-response.dto.ts
gasless-gossip/src/reputation/dto/reputation-response.dto.ts
gasless-gossip/src/reputation/dto/update-reputation-settings.dto.ts
gasless-gossip/src/reputation/enums/reputation-change-type.enum.ts
gasless-gossip/src/reputation/enums/reputation-factor.enum.ts
gasless-gossip/src/reputation/enums/reputation-level.enum.ts
gasless-gossip/src/reputation/interfaces/reputation-history.interface.ts
gasless-gossip/src/reputation/interfaces/reputation-settings.interface.ts
gasless-gossip/src/reputation/interfaces/reputation.interface.ts
gasless-gossip/src/reputation/reputation.controller.ts
gasless-gossip/src/reputation/reputation.module.ts
gasless-gossip/src/reputation/schemas/reputation-history.schema.ts
gasless-gossip/src/reputation/schemas/reputation-settings.schema.ts
gasless-gossip/src/reputation/schemas/reputation.schema.ts
gasless-gossip/src/reputation/schemas/reputation.service.ts
gasless-gossip/src/reputation/tests/reputation.service.spec.ts

**This PR introduces a reputation system that tracks user trustworthiness and contributions within the Gasless Gossip community. It defines a structured reputation model, scoring algorithm, event-driven updates, and API endpoints for querying reputation data.**
**Tasks Completed**
✅ Reputation Model & Metrics – Defined the reputation resource structure and key metrics.
✅ Reputation Scoring Algorithm – Implemented a system for calculating reputation based on various factors.
✅ ReputationService – Handles score calculation and updates.
✅ Event Listeners – Triggers updates based on user actions.
✅ Reputation Levels – Introduced tiers to classify users based on scores.
✅ Reputation History Tracking – Logs changes over time for transparency.
✅ ReputationController & API Endpoints – Provides …

Add reputation system with enums, DTOs, interfaces, and schemas

---

README.md
gasless-gossip/src/auth/dto/authCredential.dto.ts
gasless-gossip/src/auth/dto/register.user.dto.ts
gasless-gossip/src/auth/interfaces/auth-response.interface.ts
gasless-gossip/src/auth/interfaces/interface.jwt.ts
gasless-gossip/src/auth/interfaces/logout.response.interface.ts
gasless-gossip/src/auth/models/refresh-token.model.ts
gasless-gossip/src/auth/models/token.response.model.ts
gasless-gossip/src/auth/provider/bcrypt.ts
gasless-gossip/src/auth/provider/hashing.ts
gasless-gossip/src/utils/password-validation.ts

Core authentication for resource model

Core authentication for resource model

---

gasless-gossip/src/storage/services/storage.service.ts
gasless-gossip/src/storage/storage.module.ts
gasless-gossip/src/users/controllers/user.controller.ts
gasless-gossip/src/users/dto/change-password.dto.ts
gasless-gossip/src/users/dto/create-user.dto.ts
gasless-gossip/src/users/dto/response.dto.ts
gasless-gossip/src/users/dto/update-profile.dto.ts
gasless-gossip/src/users/entities/user.entity.ts
gasless-gossip/src/users/services/user.service.ts
gasless-gossip/src/users/test/user.controller.spec.ts
gasless-gossip/src/users/test/user.service.spec.ts
gasless-gossip/src/users/users.module.ts

This PR introduces the **User Profile Service and Controller**, enabling comprehensive management of user profiles.
close #18
✅ Implemented **UserService** with profile operations  
✅ Created **UserController** with CRUD endpoints  
✅ Added **input validation** using DTOs  
✅ Implemented **profile picture handling** (upload & retrieval)  
✅ Ensured **username uniqueness validation** to prevent conflicts  
🔹 All **CRUD operations** for profiles work correctly  
🔹 **Input validation** prevents invalid data submissions  
🔹 Users can **upload and retrieve** profile pictures  
🔹 **Username conflicts** are properly handled  
🔹 **Endpoints are documented** for easy integration  
This implementation ensures a robust and scalable user profile system. 🚀

User-Profile-Service-and-Controller

---

gasless-gossip/src/auth/decorators/current-user.decorator.ts
gasless-gossip/src/conversation/controllers/conversation.controller.ts
gasless-gossip/src/conversation/conversation.module.ts
gasless-gossip/src/conversation/dtos/add-participants.dto.ts
gasless-gossip/src/conversation/dtos/conversation-response.dto.ts
gasless-gossip/src/conversation/dtos/create-conversation.dto.ts
gasless-gossip/src/conversation/dtos/pagination.dto.ts
gasless-gossip/src/conversation/dtos/update-conversation.dto.ts
gasless-gossip/src/conversation/schema/conversation.schema.ts
gasless-gossip/src/conversation/services/conversation.service.ts
gasless-gossip/src/conversation/test/conversation.controller.spec.ts
gasless-gossip/src/conversation/test/conversation.e2e-spec.ts
gasless-gossip/src/conversation/test/conversation.service.spec.ts

created conversation folder

---

gasless-gossip/src/group-room/base-repository.ts
gasless-gossip/src/group-room/group-dtos.ts
gasless-gossip/src/group-room/group-membership-repository.ts
gasless-gossip/src/group-room/group-membership-schema.ts
gasless-gossip/src/group-room/group-module.ts
gasless-gossip/src/group-room/group-repository-test.ts
gasless-gossip/src/group-room/group-repository.ts
gasless-gossip/src/group-room/group-schema.ts

This PR implements a structured and efficient approach to managing groups and memberships using Mongoose.
Key Changes:
Group Repository: Implements CRUD operations for managing groups.
Group Membership Schema: Establishes user-group relationships.
Optimized Queries: Adds indexing for improved query performance.
Group Membership Repository: Enables efficient membership management.
Unit Testing: Ensures repository methods function correctly.
Modular Design: Enhances maintainability and scalability.
This update improves performance, reliability, and organization of group-related operations.

Add group room

---

gasless-gossip/src/starknet-provider/provider-dtos.ts
gasless-gossip/src/starknet-provider/provider-exception.ts
gasless-gossip/src/starknet-provider/provider-interface.ts
gasless-gossip/src/starknet-provider/provider-interfaces.ts
gasless-gossip/src/starknet-provider/provider-module.ts
gasless-gossip/src/starknet-provider/provider-service-test.ts
gasless-gossip/src/starknet-provider/provider-service.ts

Resolves #16 
I implemented a robust service for handling connections to StarkNet nodes for Gasless Gossip. The solution manages connections to various provider types while incorporating fault tolerance, performance optimization, and comprehensive monitoring.
- Defined clear enums for network types (MAINNET, TESTNET, etc.) and provider types (RPC, SEQUENCER, INFURA, ALCHEMY).
- Created strongly typed interfaces for each provider's configuration options.
- Established network information interface for status tracking and health monitoring.
- Implemented a hierarchy of DTOs with validation using `class-validator`.
- Used discriminated unions for type-safe provider configuration.
- Added sensible defaults for timeouts, retries, and caching parameters.
- Created a global NestJS module for …

Ot nest stknt prov serv

---

gasless-gossip/src/conversation/schema/conversation.schema.ts
gasless-gossip/src/messaging/controllers/message.controller.ts
gasless-gossip/src/messaging/dto/create-message.dto.ts
gasless-gossip/src/messaging/dto/group-message-response.dto.ts
gasless-gossip/src/messaging/dto/pin-message.dto.ts
gasless-gossip/src/messaging/gateways/messaging.gateway.ts
gasless-gossip/src/messaging/schemas/message.schema.ts
gasless-gossip/src/messaging/services/message.service.ts
gasless-gossip/src/messaging/test/message.service.spec.ts
gasless-gossip/src/messaging/test/messaging.gateway.e2e-spec.ts

implemented group messaging

---

gasless-gossip/src/notifications/controllers/notification.controller.ts
gasless-gossip/src/notifications/dto/batch-update.dto.ts
gasless-gossip/src/notifications/dto/notification.dto.ts
gasless-gossip/src/notifications/dto/pagination.dto.ts
gasless-gossip/src/notifications/entities/notification.entity.ts
gasless-gossip/src/notifications/interfaces/notification-type.enum.ts
gasless-gossip/src/notifications/listeners/conversation.listener.ts
gasless-gossip/src/notifications/listeners/index.ts
gasless-gossip/src/notifications/listeners/message.listener.ts
gasless-gossip/src/notifications/listeners/transfer.listener.ts
gasless-gossip/src/notifications/notification.gateway.ts
gasless-gossip/src/notifications/notification.module.ts
gasless-gossip/src/notifications/services/notification.service.ts
gasless-gossip/src/notifications/test/notification.controller.spec.ts
gasless-gossip/src/notifications/test/notification.service.spec.ts

#21 User Notification system

---

gasless-gossip/src/blockchain/blockchain.module.ts
gasless-gossip/src/blockchain/services/starknet-provider.service.ts
gasless-gossip/src/transfers/controllers/token-transfer.controller.ts
gasless-gossip/src/transfers/dto/fee-estimate.dto.ts
gasless-gossip/src/transfers/dto/token-transfer.dto.ts
gasless-gossip/src/transfers/dto/transaction-status.dto.ts
gasless-gossip/src/transfers/entities/transaction.entity.ts
gasless-gossip/src/transfers/interfaces/token-transfer.interface.ts
gasless-gossip/src/transfers/interfaces/token-type.enum.ts
gasless-gossip/src/transfers/interfaces/transaction-status.interface.ts
gasless-gossip/src/transfers/services/fee-estimation.service.ts
gasless-gossip/src/transfers/services/token-transfer.service.ts
gasless-gossip/src/transfers/services/transaction-status.service.ts
gasless-gossip/src/transfers/test/token-transfer.service.spec.ts
gasless-gossip/src/transfers/transfers.gateway.ts
gasless-gossip/src/transfers/transfers.module.ts

Token Transfer Service
